// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAIMopDd3XZKlV3vnF9R_UIOMe7na4k5c',
    appId: '1:101203829085:web:d5b64afd6d13577ef7c8b4',
    messagingSenderId: '101203829085',
    projectId: 'freshfare-f7702',
    authDomain: 'freshfare-f7702.firebaseapp.com',
    storageBucket: 'freshfare-f7702.firebasestorage.app',
    measurementId: 'G-6CRD2K78PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1VopNtD1xcxE9Squ6xHXfpxiQ6lMdvOM',
    appId: '1:101203829085:android:5f023e87594bdfa7f7c8b4',
    messagingSenderId: '101203829085',
    projectId: 'freshfare-f7702',
    storageBucket: 'freshfare-f7702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDedM9lVeZKAviBqrlGqTBOSi_3ONtM1mI',
    appId: '1:101203829085:ios:48291de8d7091df6f7c8b4',
    messagingSenderId: '101203829085',
    projectId: 'freshfare-f7702',
    storageBucket: 'freshfare-f7702.firebasestorage.app',
    iosBundleId: 'com.example.freshfare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDedM9lVeZKAviBqrlGqTBOSi_3ONtM1mI',
    appId: '1:101203829085:ios:48291de8d7091df6f7c8b4',
    messagingSenderId: '101203829085',
    projectId: 'freshfare-f7702',
    storageBucket: 'freshfare-f7702.firebasestorage.app',
    iosBundleId: 'com.example.freshfare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAIMopDd3XZKlV3vnF9R_UIOMe7na4k5c',
    appId: '1:101203829085:web:3b306a9656efc662f7c8b4',
    messagingSenderId: '101203829085',
    projectId: 'freshfare-f7702',
    authDomain: 'freshfare-f7702.firebaseapp.com',
    storageBucket: 'freshfare-f7702.firebasestorage.app',
    measurementId: 'G-Q2CK27F3MX',
  );
}
